# Generated by Django 2.2 on 2019-06-23 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='_userprofile_contacts_+', to='accounts.UserProfile')),
            ],
        ),
    ]
